FROM ghcr.io/ublue-os/ucore-minimal:stable@sha256:a9c7ed1277e400e6742fd6c11d13294ff5072de6caf6462fe410dfebfdabb718

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    ostree container commit

RUN bootc container lint
